version: 1.2
tools:
   - subclass: cwl
     primaryDescriptorPath: /tools/Dockstore.cwl
     name: md5sum
workflows:
   - subclass: cwl
     primaryDescriptorPath: /workflows/HelloWorld.cwl
service:
   subclass: NOT_APPLICABLE
   name: fake-service
   files:
     - README.md
   scripts:
     start: README.md
