version: 1.2
tools:
   - subclass: cwl
     primaryDescriptorPath: /tools/Dockstore.cwl
workflows:
   - subclass: cwl
     primaryDescriptorPath: /workflows/HelloWorld.cwl
service:
   - subclass: DOCKER_COMPOSE
     name: fake-service
     files:
       - README.md
